### ISSUE TITLE
Rig is wrong, are you stil work to the project?

### ISSUE THREAD

**Issue by Justin-sky** [BrandonBartram98/MediaPipe-UnitySolver#2]
![image](https://user-images.githubusercontent.com/58215826/204429123-b1cd4d03-dece-4dcd-92a4-2e7e4f9c0d05.png)

**Comment by BrandonBartram98** [comment]
The pose solver was a work in-progress based on the Moetion library and currently isn't usable as I found out they use a different rig type. So will be working on a different implementation at some point.
